In [2]:
!pip install numpy

In [3]:
!pip install pandas

In [4]:
!pip install matplotlib

In [5]:
!pip install scikit-learn

In [12]:
a=[1, 2, 3]
a

[1, 2, 3]

In [14]:
import numpy as np

In [19]:
a = np.array([1, 2, 3])

In [20]:
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [26]:
arr2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

In [27]:
a = np.array(arr2)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
a.ndim
a.shape

(4, 3)

In [31]:
arr = []
for i in range(10):
    arr.append(0)
print(arr)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [32]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [41]:
np.full(5, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

In [42]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [61]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [64]:
np.random.random(10)

array([0.95343062, 0.41161156, 0.94317262, 0.53375973, 0.82586592,
       0.39436869, 0.72300516, 0.96805073, 0.46040712, 0.85999245])

In [72]:
np.random.random(( 5, 3))

array([[0.0966486 , 0.93612879, 0.19102919],
       [0.9819123 , 0.34012179, 0.88061952],
       [0.12675942, 0.71738156, 0.3678643 ],
       [0.71969182, 0.68363824, 0.64726083],
       [0.25164389, 0.64840262, 0.16903379]])

In [74]:
np.zeros(5, dtype=float)

array([0., 0., 0., 0., 0.])

In [78]:
np.random.randint(0, 6)

4

In [85]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
a.size

9

In [88]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [91]:
b = a.reshape((2,3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
b.flatten()

array([0, 1, 2, 3, 4, 5])

In [126]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [123]:
a.reshape((6, 1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [129]:
a.reshape((6, -1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [131]:
np.arange(16).reshape((-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [135]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[:2])
print(data[:])

2
[1 2]
[1 2]
[1 2 3]


In [137]:
data[0] = 5 
data

array([5, 2, 3])

In [141]:
a = np.arange(6)
a 

array([0, 1, 2, 3, 4, 5])

In [146]:
a == 3

array([False, False, False,  True, False, False])

In [147]:
arr = []
for i in a:
    if i < 3: 
        arr.append(i)
arr

[0, 1, 2]

In [148]:
a[ a < 3]

array([0, 1, 2])

In [169]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3]])

In [152]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [154]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [174]:
a = np.arange(6)
b = a.copy()
b[0] = -1

print(a)
print(b)

[0 1 2 3 4 5]
[-1  1  2  3  4  5]


In [172]:
data = np.arange(2)
ones = np.ones(2)

print(data, ones)

[0 1] [1. 1.]


In [164]:
data + ones 

array([1., 2.])

In [165]:
data - ones

array([-1.,  0.])

In [166]:
data * ones 

array([0., 1.])

In [171]:
data / ones

C:\Users\user\AppData\Local\Temp\ipykernel_9028\514225964.py:1: RuntimeWarning: divide by zero encountered in divide
  data / ones
C:\Users\user\AppData\Local\Temp\ipykernel_9028\514225964.py:1: RuntimeWarning: invalid value encountered in divide
  data / ones


array([nan, inf])

In [176]:
data

array([0, 1])

In [182]:
data.reshape(2, 1)  / 5

array([[0. ],
       [0.2]])

In [181]:
np.full(3, 6)

array([6, 6, 6])

In [183]:
data = np.arange(10)

In [184]:
print(data.max())
print(data.min())
print(data.sum())
print(data.mean())
print(data.std())


9
0
45
4.5
2.8722813232690143


In [188]:
theta = np.linspace(0, 1, 5)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))
print(np.exp(theta))

theta      =  [0.   0.25 0.5  0.75 1.  ]
sin(theta) =  [0.         0.24740396 0.47942554 0.68163876 0.84147098]
cos(theta) =  [1.         0.96891242 0.87758256 0.73168887 0.54030231]
tan(theta) =  [0.         0.25534192 0.54630249 0.93159646 1.55740772]
[1.         1.28402542 1.64872127 2.11700002 2.71828183]


In [201]:
mat = np.arange(16).reshape(-4, 4)

print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [196]:
mat.max(axis=1)

array([ 3,  7, 11, 15])

In [206]:
mat[:, 1]

array([ 1,  5,  9, 13])

In [208]:
mat[2:, 2:]

array([[10, 11],
       [14, 15]])

In [209]:
np.save("numpy-1", mat)

In [210]:
np.load("numpy-1.npy")

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [211]:
# np operations are much faster
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

135 ms ± 15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.71 ms ± 254 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
y_hat = np.array([1, 2.2, 2.9])
y = np.array([1, 2, 3])

loss = np.mean(np.square(y_hat - y))
print(loss)

In [212]:
y_hat = np.array([1, 2.2, 2.9])
y = np.array([1, 2, 3])

In [216]:
np.mean(np.square(y_hat - y))

0.016666666666666694

# Pandas

In [217]:
!pip install pandas

In [3]:
import pandas as pd 

In [4]:
a = pd.read_csv('music.csv')

In [5]:
titanic_df =  pd.read_csv("titanic.csv")

In [6]:
df.shape

NameError: name 'df' is not defined

In [235]:
df.head()

age  gender   genre
0   20       1  HipHop
1   23       1  HipHop
2   25       1  HipHop
3   26       1    Jazz
4   29       1    Jazz

In [236]:
df.tail()

age  gender      genre
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [238]:
df.head(10)

age  gender      genre
0   20       1     HipHop
1   23       1     HipHop
2   25       1     HipHop
3   26       1       Jazz
4   29       1       Jazz
5   30       1       Jazz
6   31       1  Classical
7   33       1  Classical
8   37       1  Classical
9   20       0      Dance

In [7]:
df.to_csv("music-new.csv", index=False)

NameError: name 'df' is not defined

In [243]:
X = df[['age', 'gender']]
print(X)
y = df['genre']

    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0


In [245]:
X[:5]

age  gender
0   20       1
1   23       1
2   25       1
3   26       1
4   29       1

In [246]:
y[:5]

0    HipHop
1    HipHop
2    HipHop
3      Jazz
4      Jazz
Name: genre, dtype: object

In [8]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X, y)



NameError: name 'X' is not defined

In [250]:
model.predict([
    [22, 1], 
    [38, 1]
])

c:\Users\user\anaconda3\envs\plotting\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['HipHop', 'Classical'], dtype=object)