In [2]:
# conda install numpy pandas /* this command on terminal */
!pip install numpy pandas

In [3]:
!pip install matplotlib scikit-learn

# NumPy

In [4]:
[1, 2, 3, 4,]

[1, 2, 3, 4]

In [5]:
import numpy as np


In [6]:
a = np.array([1, 2, 3])

In [7]:
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
arr2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
]

In [9]:
a = np.array(arr2)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
print(a.ndim)
print(a.shape)

2
(4, 3)


In [11]:
arr3 = []
for i in range(10):
    arr3.append(0)
print(arr3)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(100)
# np.ones(6)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [15]:
np.full(5, 15)

array([15, 15, 15, 15, 15])

In [16]:
np.full(7, 3.1416)

array([3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416])

In [17]:
range(10)

range(0, 10)

In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0, 1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [21]:
np.empty(17)

array([4.67296746e-307, 1.69121096e-306, 9.34609111e-307, 1.11256817e-306,
       1.06811422e-306, 1.42417221e-306, 1.11260619e-306, 8.90094053e-307,
       1.86919378e-306, 1.06809792e-306, 1.37962456e-306, 1.69111861e-306,
       1.78020169e-306, 1.37961777e-306, 7.56599807e-307, 6.97843598e+252,
       6.80167383e-310])

In [22]:
np.random.random(10)

array([0.3684496 , 0.19793703, 0.30579734, 0.8401773 , 0.77975497,
       0.88880695, 0.20866065, 0.97254682, 0.45072389, 0.43602757])

In [23]:
np.zeros((2, 5, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
np.random.random((3, 2, 5))

array([[[0.09477364, 0.29333783, 0.09202939, 0.25391145, 0.78113865],
        [0.93786769, 0.17048689, 0.32263159, 0.22998419, 0.231764  ]],

       [[0.00802752, 0.52958335, 0.37530302, 0.32857933, 0.98030267],
        [0.03090427, 0.24882309, 0.71037774, 0.8868151 , 0.1046846 ]],

       [[0.08272171, 0.66435815, 0.44916881, 0.04886988, 0.39469647],
        [0.28817408, 0.19037351, 0.92061858, 0.00732803, 0.89748213]]])

In [25]:
np.random.uniform((2, 5))

array([1.91166617, 3.65607041])

In [26]:
np.zeros(6, dtype=float)

array([0., 0., 0., 0., 0., 0.])

In [27]:
np.random.randint(0, 5)

0

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
a = np.eye(5)

In [30]:
a.size

25

In [31]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [32]:
a.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
b = a.reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
b.flatten()

array([0, 1, 2, 3, 4, 5])

In [35]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [36]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [37]:
array = np.arange(16)
array.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
array = np.arange(16).reshape(4, 4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
np.arange(16).reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
np.arange(16).reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[:2])
print(data[:])

2
[1 2]
[2 3]
[1 2]
[1 2 3]


In [42]:
data[0] = 5
data

array([5, 2, 3])

In [43]:
a = np.arange(10)

In [44]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [45]:
a[a < 6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arr = []
for i in a:
    if i < 4:
        arr.append(i)
arr

[0, 1, 2, 3]

In [47]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [48]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [49]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [50]:
a = np.arange(6)
b = a.copy()
b[0] = -1

print(a)
print(b)

[0 1 2 3 4 5]
[-1  1  2  3  4  5]


In [51]:
data = np.arange(2)
ones = np.zeros(2)
print(data, ones)

[0 1] [0. 0.]


In [52]:
data + ones

array([0., 1.])

In [53]:
data - ones

array([0., 1.])

In [54]:
data * ones

array([0., 0.])

In [55]:
data / ones

C:\Users\user\AppData\Local\Temp\ipykernel_9396\514225964.py:1: RuntimeWarning: divide by zero encountered in divide
  data / ones
C:\Users\user\AppData\Local\Temp\ipykernel_9396\514225964.py:1: RuntimeWarning: invalid value encountered in divide
  data / ones


array([nan, inf])

In [56]:
data + 6

array([6, 7])

In [57]:
data.reshape(-1, 1) + 5

array([[5],
       [6]])

In [58]:
data.reshape(-1, 1) - 5

array([[-5],
       [-4]])

In [59]:
data.reshape(-1, 1) * 5

array([[0],
       [5]])

In [60]:
data.reshape(-1, 1) / 5

array([[0. ],
       [0.2]])

In [61]:
np.full(3, 6)

array([6, 6, 6])

In [62]:
data = np.arange(10)

print(data.max())
print(data.min())
print(data.sum())
print(data.mean())
print(data.std())

9
0
45
4.5
2.8722813232690143


In [63]:
theta = np.linspace(0, 1, 5)

print("theta    = ", theta)
print("sin(theta)    = ", np.sin(theta))
print("cos(theta)    = ", np.cos(theta))
print("tan(theta)    = ", np.tan(theta))

theta    =  [0.   0.25 0.5  0.75 1.  ]
sin(theta)    =  [0.         0.24740396 0.47942554 0.68163876 0.84147098]
cos(theta)    =  [1.         0.96891242 0.87758256 0.73168887 0.54030231]
tan(theta)    =  [0.         0.25534192 0.54630249 0.93159646 1.55740772]


In [64]:
mat = np.arange(16).reshape(-1, 4)

print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [65]:
mat.max(axis=0)

array([12, 13, 14, 15])

In [66]:
mat.max(axis=1)

array([ 3,  7, 11, 15])

In [67]:
mat[1]

array([4, 5, 6, 7])

In [68]:
mat[1, 3]

7

In [69]:
mat[:, 2]

array([ 2,  6, 10, 14])

In [70]:
mat[2:, 2:]

array([[10, 11],
       [14, 15]])

In [71]:
np.save("numpy-1", mat)

In [72]:
np.load("numpy-1.npy")

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

466 ms ± 167 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.42 ms ± 926 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [74]:
y_hat = np.array([1, 2.2, 2.9])
y = np.array([1, 2, 3])

loss = np.mean(np.square(y_hat - y))
print(loss)

0.016666666666666694


# Pandas

In [75]:
import pandas as pd

In [76]:
pd.read_csv("music.csv")

age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [77]:
pd.read_csv("music.csv", sep = ",")

age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [78]:
pd.read_csv("music.csv", sep = ",", header=0)

age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [96]:
music_df = pd.read_csv("music.csv", sep = ",")

type(music_df)

pandas.core.frame.DataFrame

In [80]:
titanic_df = pd.read_csv("titanic.csv")

In [81]:
titanic_df.shape

(891, 12)

In [82]:
titanic_df.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                     

In [83]:
titanic_df.tail

<bound method NDFrame.tail of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                     

In [84]:
titanic_df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [85]:
music_df = pd.read_csv("music.csv", sep=",")

In [86]:
music_df.shape

(18, 3)

In [87]:
music_df.head

<bound method NDFrame.head of     age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical>

In [88]:
music_df.tail

<bound method NDFrame.tail of     age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical>

In [89]:
music_df.head(10)

age  gender      genre
0   20       1     HipHop
1   23       1     HipHop
2   25       1     HipHop
3   26       1       Jazz
4   29       1       Jazz
5   30       1       Jazz
6   31       1  Classical
7   33       1  Classical
8   37       1  Classical
9   20       0      Dance

In [90]:
music_df.to_csv("music-new.csv", index=False)

In [91]:
X = music_df[['age', 'gender']]
print(X)
y = music_df[['genre']]


    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0


In [92]:
X[:5]

age  gender
0   20       1
1   23       1
2   25       1
3   26       1
4   29       1

In [93]:
y[:5]

genre
0  HipHop
1  HipHop
2  HipHop
3    Jazz
4    Jazz

In [94]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X, y)

model.predict([
    [22, 1],
    [39, 1]
])

d:\Intro_to_AI-BKIAC\.conda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['HipHop', 'Classical'], dtype=object)