In [1]:

one_d = [1, 2, 3]
two_d = [
    one_d,
    one_d,
    one_d
]

In [3]:
import numpy as np

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
np.array(one_d)

array([1, 2, 3])

In [23]:
a = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])

In [24]:
np.array(two_d, dtype=np.float32)
np.array(two_d, dtype='float')

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [22]:
# np.array([range(i , i + 3) for i in [1]])

In [21]:
# a = np.array([range(i , i + 3) for i in [1, 4, 7]])
# a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
print(a[0])

[1 2 3 4]


#### Create basic array

In [26]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((2,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
# all zeros 

np.zeros(shape=(3, 5), dtype=np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [217]:
np.empty(3)

array([ 6.95265408e-310,  7.33039255e-312, -0.00000000e+000])

In [33]:
# Create a 3x5 array filled with 3.14
np.full(4, 3.14)

array([3.14, 3.14, 3.14, 3.14])

In [219]:
print(range(5))
print(list(range(5)))

range(0, 5)
[0, 1, 2, 3, 4]


In [220]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [222]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)

# np.arange(0, 20, 2).reshape(5, 2)

In [223]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [225]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random(5)

array([0.41341805, 0.28646174, 0.39229332, 0.5202328 , 0.85877615])

In [46]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.93760121, -0.39383089, -1.01697563],
       [ 0.73135224, -0.35087877,  1.64714613],
       [ 0.07584314,  0.10047465,  0.89025085]])

In [43]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [230]:
a = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])


In [231]:
a.shape

2

In [232]:
a.size

9

In [235]:
a.ndim

2

#### Reshaping
[link](https://numpy.org/doc/stable/user/absolute_beginners.html#transposing-and-reshaping-a-matrix)

In [241]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [243]:
b = a.reshape(2,3)

print(b)

[[0 1 2]
 [3 4 5]]


In [245]:
c = a.reshape(2, -1)
print(c)

[[0 1 2]
 [3 4 5]]


In [280]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [281]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Indexing

In [246]:
data = np.array([1, 2, 3])
print(data[1])
print(data[0:2])
print(data[:2])

2
[1 2]
[1 2]


In [250]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [249]:
a[a < 5]

array([0, 1, 2, 3, 4])

In [251]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False])

In [253]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [254]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [255]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [256]:
a_ = a1.copy()

# Calculations 
[link](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)

In [259]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [260]:
data + ones

array([2, 3])

In [261]:
data - ones

array([0, 1])

In [262]:
data * data

array([1, 4])

In [263]:
data / data

array([1., 1.])

In [265]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [269]:
b = np.array([[1, 1], [2, 2], [3, 3]])
print(b)

[[1 1]
 [2 2]
 [3 3]]


In [268]:
b.sum(axis=0)

array([6, 6])

In [270]:
b.sum(axis=1)

array([2, 4, 6])

In [271]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [274]:
print(data.max())
print(data.min())
print(data.sum())
print(data.mean())
print(data.std())


6
1
21
3.5
1.707825127659933


Matrix

In [272]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data


array([[1, 2],
       [3, 4],
       [5, 6]])

In [275]:
data[0, 1]


2

In [276]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [277]:
data[0:2, 0]

array([1, 3])

In [278]:
data.max(axis=0)

array([5, 6])

In [279]:
data.max(axis=1)

array([2, 4, 6])

Calculating Loss

[link](https://numpy.org/doc/stable/user/absolute_beginners.html#working-with-mathematical-formulas)

In [284]:
y_hat = np.array([1, 2.2, 2.9])
y = np.array([1, 2, 3])

loss = np.mean(np.square(y_hat - y))
print(loss)

0.016666666666666694


Save to file

In [288]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [285]:
np.save("numpy-array", data)

In [287]:
read_data = np.load("numpy-array.npy")
print(read_data)

[[1 2]
 [3 4]
 [5 6]]


# Basics of numpy array

In [78]:
import numpy as np
np.random.seed(42)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x1)

[6 3 7 4 6 9]


In [79]:
x1

array([6, 3, 7, 4, 6, 9])

In [84]:
print(x2)
print(x2[0, 0])

[[2 6 7 4]
 [3 7 7 2]
 [5 4 1 7]]
2


In [85]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 3, 7, 4, 6, 9])

In [88]:
x = np.arange(10)
y = x 
z = x.copy()
z[0 ] = -1
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([4, 4, 4])

In [91]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])


In [92]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [94]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [95]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [96]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [98]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [99]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [100]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [101]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [102]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [289]:
# np operations are much faster
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

82.2 ms ± 1.76 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.11 ms ± 85.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [104]:
np.min(big_array), np.max(big_array)

(2.27627054061319e-06, 0.9999993140659148)

In [9]:
M = np.arange(9).reshape((3,3))
print(M)
print(np.sum(M, axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]
