In [3]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

X = torch.tensor(1., requires_grad = True)
w = torch.tensor(2., requires_grad = True)
b = torch.tensor(3., requires_grad = True)

y = w * X + b

y.backward()

print(X.grad)
print(w.grad)
print(b.grad)

tensor(2.)
tensor(1.)
tensor(1.)


In [4]:
X = torch.randn(10, 3)
y = torch.randn(10, 2)

linear = nn.Linear(3, 2)

print('w : ',linear.weight)
print('b : ',linear.bias)

w :  Parameter containing:
tensor([[-0.2157,  0.1310,  0.3051],
        [ 0.4451, -0.3404, -0.2396]], requires_grad=True)
b :  Parameter containing:
tensor([-0.3275,  0.3592], requires_grad=True)


In [7]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

pred = linear(X)

loss = criterion(pred, y)
print('loss : ', loss.item())

loss :  1.2837666273117065


In [8]:
loss.backward()
print('dl/dw : ', linear.weight.grad)
print('dl/db : ', linear.bias.grad)

dl/dw :  tensor([[-0.4653,  0.9008, -0.4911],
        [ 0.2420, -0.3081,  0.1396]])
dl/db :  tensor([-0.5989,  0.4778])


In [9]:
optimizer.step()

linear.weight.data.sub_(0.01 * linear.weight.grad.data)
linear.bias.data.sub_(0.01 * linear.bias.grad.data)

tensor([-0.3156,  0.3496])

In [10]:
pred = linear(X)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

loss after 1 step optimization:  1.2439603805541992


In [ ]:
X = np.array([[1, 2], [3, 4]])
y = torch.from_numpy(X)
